#!/bin/bash
set -e

# Jó helyen vagyunk?
test -f config.toml

rm -rf public
zola build

find public -name '*.html' -print0 \
    | xargs -0 -I@@ /bin/sed -i -E -e 's|(=[\x22\x27]?)https://szabadulas.github.io/|\1/|g' @@
