base_url = "https://szabadulas.github.io"

output_dir = "public"

compile_sass = true
build_search_index = false
minify_html = true
generate_feed = false

[markdown]
highlight_code = false
render_emoji = false
smart_punctuation = false
