base_url = "https://szabadulas.github.io"

output_dir = "public"

compile_sass = true
build_search_index = false
minify_html = true
generate_feeds = false

[markdown]
highlight_code = true
render_emoji = false
smart_punctuation = false
