#!/bin/bash
set -e

# Jó helyen vagyunk?
test -f config.toml

if [ "$(git branch --show-current)" != main ]; then
    echo "$0: Not on 'main' branch. Aborting."
    exit 1
fi

if [ "$(git status --short)" != '' ]; then
    echo "$0: 'main' branch has uncommitted changes:"
    echo
    git status --short
    echo
    read -s -p 'Ctrl-C: ABORT.  Enter: CONTINUE ANYWAY. '
    echo
fi

./build

cd public
git init -b main
git add .
git commit -m 'Deploy'
git push --force ../ main:gh-pages

cd ..
git push --force origin gh-pages:gh-pages
