#!/bin/bash
set -e -x

# Jó helyen vagyunk?
test -f config.toml

./build

cd public
git init
git add .
git commit -m 'Deploy'
git push --force 'https://github.com/szabadulas/szabadulas.github.io.git' master:gh-pages
